console.log("Swap two names :");
var name1="Sweety";
var name2="Cutey";
console.log("Before Swap : ", "name1 =>", name1 ,"name2 =>", name2);
var tempName=name1;
name1=name2;
name2=tempName;
console.log("After Swap : ", "name1 =>", name1 ,"name2 =>", name2);
console.log("---------------------------------------------");
console.log("Swap Three Numbers :");
var num1=10;
var num2=20;
var num3=30;
console.log("Before Swap", "num1 ==> ", num1 ,"num2 ==> ",num2, "num3 ==> ",num3);
var tempNum=num1;
num1=num2;
num2=num3;
num3=tempNum;
console.log("After Swap", "num1 ==> ", num1 ,"num2 ==> ",num2, "num3 ==> ",num3);