console.log("---------- Implicit conversion of String to Number ----------");
var result;
result = "4" - "2";
console.log(`Type of result is : ${typeof result}and result is : ${result}`);
result = "4" - 2;
console.log(`Result is : ${result} and type of result is : ${typeof result}`);
result = "4" * 2;
console.log(`Result is : ${result} and type of result is : ${typeof result}`);
result = "4" / 2;
console.log(`Result is : ${result} and type of result is : ${typeof result}`);
console.log("Because, when we perform arithmetic operation on string then string converted into number \nthat is Implicit conversion of String to Number\n");

console.log("---------- Implicit conversion ot String ----------");
result = "3" + 2;
console.log(`Result is : '${result}' and type of result is : ${typeof result}`);
result = "3" + true;
console.log(`Result is : '${result}' and type of result is : ${typeof result}`);
result = "3" + undefined;
console.log(`Result is : '${result}' and type of result is : ${typeof result}`);
result = "3" + null;
console.log(`Result is : '${result}' and type of result is : ${typeof result}`);
console.log("Because, when we add other data type or object into the string type then '+' operator can \nconverts into string type, that is Implicit conversion ot String\n");

console.log("---------- Implicit conversion of Boolean to Number ----------");
result = "4" - true;
console.log(`Result is : ${result} and type of result is : ${typeof result}`);
result = 4 + true;
console.log(`Result is : ${result} and type of result is : ${typeof result}`);
result = 4 + false;
console.log(`Result is : ${result} and type of result is : ${typeof result}`);
console.log("Because, when we perform arithmetic operation on boolean data type then it will be \nconverted into number that is Implicit conversion of Boolean to Number\n");

console.log("---------- Some other few interesting facts using == operator -----------");
result=0==' ';
console.log("1) result = 0 == ' ' ");
console.log(`Result is : ${result} and type of result is : ${typeof result}`);
result=0=='0';
console.log("2) result = 0 == '0' ");
console.log(`Result is : ${result} and type of result is : ${typeof result}`);
result=1=='1';
console.log("3) result = 1 == '1' ");
console.log(`Result is : ${result} and type of result is : ${typeof result}`);
console.log("Because, when we use '==' operator on string data type then it will be converted into number");
result=0==false;
console.log("4) result = 0 == false ");
console.log(`Result is : ${result} and type of result is : ${typeof result}`);
result=1==true;
console.log("5) result = 1 == true ");
console.log(`Result is : ${result} and type of result is : ${typeof result}`);
console.log("Because, when we use '==' operator on boolean data type then it will be converted into number");
result=null==undefined;
console.log("6) result = null == undefined ");
console.log(`Result is : ${result} and type of result is : ${typeof result}`);
console.log("Because, same values of null and undefined that is empty or blank");
result=1==[1];
console.log("7) result = 1 == [1] ");
console.log(`Result is : ${result} and type of result is : ${typeof result}`);
console.log("Because, same values that is 1 and 1");
console.log("\n");